name: 'task-manager-ui'
replicaCount: 1

images:
  PullSecrets:
    name: kartoffelreg
  repository: genesisproject.azurecr.io/task-manager-ui
  tag: 'latest'

service:
  type: ClusterIP
  ports:
    - name: http
      port: 80

config:
  configmaps:
    name: task-manager-ui
